version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  server:
    depends_on:
      - mysqldb
    build: ./
    container_name: server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - ./server:/app
    links:
      - mysqldb
    command: npm run dev
    stdin_open: true
    tty: true

volumes: 
  db:

networks:
  internalnet:
    driver: bridge