exports.data = [
  { name: 'Adilabad', state_id: '32', id: 1 },
  { name: 'Agra', state_id: '34', id: 2 },
  { name: 'Ahmed Nagar', state_id: '21', id: 3 },
  { name: 'Ahmedabad', state_id: '12', id: 4 },
  { name: 'Aizawl', state_id: '24', id: 5 },
  { name: 'Ajmer', state_id: '29', id: 6 },
  { name: 'Akola', state_id: '21', id: 7 },
  { name: 'Alappuzha', state_id: '18', id: 8 },
  { name: 'Aligarh', state_id: '34', id: 9 },
  { name: 'Alirajpur', state_id: '20', id: 10 },
  { name: 'Allahabad', state_id: '34', id: 11 },
  { name: 'Almora', state_id: '35', id: 12 },
  { name: 'Alwar', state_id: '29', id: 13 },
  { name: 'Ambala', state_id: '13', id: 14 },
  { name: 'Ambedkar Nagar', state_id: '34', id: 15 },
  { name: 'Amravati', state_id: '21', id: 16 },
  { name: 'Amreli', state_id: '12', id: 17 },
  { name: 'Amritsar', state_id: '28', id: 18 },
  { name: 'Anand', state_id: '12', id: 19 },
  { name: 'Ananthapur', state_id: '2', id: 20 },
  { name: 'Ananthnag', state_id: '15', id: 21 },
  { name: 'Angul', state_id: '26', id: 22 },
  { name: 'Anuppur', state_id: '20', id: 23 },
  { name: 'Araria', state_id: '5', id: 24 },
  { name: 'Ariyalur', state_id: '31', id: 25 },
  { name: 'Arwal', state_id: '5', id: 26 },
  { name: 'Ashok Nagar', state_id: '20', id: 27 },
  { name: 'Auraiya', state_id: '34', id: 28 },
  { name: 'Aurangabad', state_id: '21', id: 29 },
  { name: 'Aurangabad(BH)', state_id: '5', id: 30 },
  { name: 'Azamgarh', state_id: '34', id: 31 },
  { name: 'Bagalkot', state_id: '17', id: 32 },
  { name: 'Bageshwar', state_id: '35', id: 33 },
  { name: 'Bagpat', state_id: '34', id: 34 },
  { name: 'Bahraich', state_id: '34', id: 35 },
  { name: 'Balaghat', state_id: '20', id: 36 },
  { name: 'Balangir', state_id: '26', id: 37 },
  { name: 'Baleswar', state_id: '26', id: 38 },
  { name: 'Ballia', state_id: '34', id: 39 },
  { name: 'Balrampur', state_id: '34', id: 40 },
  { name: 'Banaskantha', state_id: '12', id: 41 },
  { name: 'Banda', state_id: '34', id: 42 },
  { name: 'Bandipur', state_id: '15', id: 43 },
  { name: 'Bangalore', state_id: '17', id: 44 },
  { name: 'Bangalore Rural', state_id: '17', id: 45 },
  { name: 'Banka', state_id: '5', id: 46 },
  { name: 'Bankura', state_id: '36', id: 47 },
  { name: 'Banswara', state_id: '29', id: 48 },
  { name: 'Barabanki', state_id: '34', id: 49 },
  { name: 'Baramulla', state_id: '15', id: 50 },
  { name: 'Baran', state_id: '29', id: 51 },
  { name: 'Bardhaman', state_id: '36', id: 52 },
  { name: 'Bareilly', state_id: '34', id: 53 },
  { name: 'Bargarh', state_id: '26', id: 54 },
  { name: 'Barmer', state_id: '29', id: 55 },
  { name: 'Barnala', state_id: '28', id: 56 },
  { name: 'Barpeta', state_id: '4', id: 57 },
  { name: 'Barwani', state_id: '20', id: 58 },
  { name: 'Bastar', state_id: '7', id: 59 },
  { name: 'Basti', state_id: '34', id: 60 },
  { name: 'Bathinda', state_id: '28', id: 61 },
  { name: 'Beed', state_id: '21', id: 62 },
  { name: 'Begusarai', state_id: '5', id: 63 },
  { name: 'Belgaum', state_id: '17', id: 64 },
  { name: 'Bellary', state_id: '17', id: 65 },
  { name: 'Betul', state_id: '20', id: 66 },
  { name: 'Bhadrak', state_id: '26', id: 67 },
  { name: 'Bhagalpur', state_id: '5', id: 68 },
  { name: 'Bhandara', state_id: '21', id: 69 },
  { name: 'Bharatpur', state_id: '29', id: 70 },
  { name: 'Bharuch', state_id: '12', id: 71 },
  { name: 'Bhavnagar', state_id: '12', id: 72 },
  { name: 'Bhilwara', state_id: '29', id: 73 },
  { name: 'Bhind', state_id: '20', id: 74 },
  { name: 'Bhiwani', state_id: '13', id: 75 },
  { name: 'Bhojpur', state_id: '5', id: 76 },
  { name: 'Bhopal', state_id: '20', id: 77 },
  { name: 'Bidar', state_id: '17', id: 78 },
  { name: 'Bijapur(CGH)', state_id: '7', id: 79 },
  { name: 'Bijapur(KAR)', state_id: '17', id: 80 },
  { name: 'Bijnor', state_id: '34', id: 81 },
  { name: 'Bikaner', state_id: '29', id: 82 },
  { name: 'Bilaspur (HP)', state_id: '14', id: 83 },
  { name: 'Bilaspur(CGH)', state_id: '7', id: 84 },
  { name: 'Birbhum', state_id: '36', id: 85 },
  { name: 'Bishnupur', state_id: '22', id: 86 },
  { name: 'Bokaro', state_id: '16', id: 87 },
  { name: 'Bongaigaon', state_id: '4', id: 88 },
  { name: 'Boudh', state_id: '26', id: 89 },
  { name: 'Budaun', state_id: '34', id: 90 },
  { name: 'Budgam', state_id: '15', id: 91 },
  { name: 'Bulandshahr', state_id: '34', id: 92 },
  { name: 'Buldhana', state_id: '21', id: 93 },
  { name: 'Bundi', state_id: '29', id: 94 },
  { name: 'Burhanpur', state_id: '20', id: 95 },
  { name: 'Buxar', state_id: '5', id: 96 },
  { name: 'Cachar', state_id: '4', id: 97 },
  { name: 'Central Delhi', state_id: '10', id: 98 },
  { name: 'Chamba', state_id: '14', id: 99 },
  { name: 'Chamoli', state_id: '35', id: 100 },
  { name: 'Champawat', state_id: '35', id: 101 },
  { name: 'Champhai', state_id: '24', id: 102 },
  { name: 'Chamrajnagar', state_id: '17', id: 103 },
  { name: 'Chandauli', state_id: '34', id: 104 },
  { name: 'Chandel', state_id: '22', id: 105 },
  { name: 'Chandigarh', state_id: '6', id: 106 },
  { name: 'Chandrapur', state_id: '21', id: 107 },
  { name: 'Changlang', state_id: '3', id: 108 },
  { name: 'Chatra', state_id: '16', id: 109 },
  { name: 'Chennai', state_id: '31', id: 110 },
  { name: 'Chhatarpur', state_id: '20', id: 111 },
  { name: 'Chhindwara', state_id: '20', id: 112 },
  { name: 'Chickmagalur', state_id: '17', id: 113 },
  { name: 'Chikkaballapur', state_id: '17', id: 114 },
  { name: 'Chitradurga', state_id: '17', id: 115 },
  { name: 'Chitrakoot', state_id: '34', id: 116 },
  { name: 'Chittoor', state_id: '2', id: 117 },
  { name: 'Chittorgarh', state_id: '29', id: 118 },
  { name: 'Churachandpur', state_id: '22', id: 119 },
  { name: 'Churu', state_id: '29', id: 120 },
  { name: 'Coimbatore', state_id: '31', id: 121 },
  { name: 'Cooch Behar', state_id: '36', id: 122 },
  { name: 'Cuddalore', state_id: '31', id: 123 },
  { name: 'Cuddapah', state_id: '2', id: 124 },
  { name: 'Cuttack', state_id: '26', id: 125 },
  { name: 'Dadra & Nagar Haveli', state_id: '8', id: 126 },
  { name: 'Dahod', state_id: '12', id: 127 },
  { name: 'Dakshina Kannada', state_id: '17', id: 128 },
  { name: 'Daman', state_id: '9', id: 129 },
  { name: 'Damoh', state_id: '20', id: 130 },
  { name: 'Dantewada', state_id: '7', id: 131 },
  { name: 'Darbhanga', state_id: '5', id: 132 },
  { name: 'Darjiling', state_id: '36', id: 133 },
  { name: 'Darrang', state_id: '4', id: 134 },
  { name: 'Datia', state_id: '20', id: 135 },
  { name: 'Dausa', state_id: '29', id: 136 },
  { name: 'Davangere', state_id: '17', id: 137 },
  { name: 'Debagarh', state_id: '26', id: 138 },
  { name: 'Dehradun', state_id: '35', id: 139 },
  { name: 'Deoghar', state_id: '16', id: 140 },
  { name: 'Deoria', state_id: '34', id: 141 },
  { name: 'Dewas', state_id: '20', id: 142 },
  { name: 'Dhalai', state_id: '33', id: 143 },
  { name: 'Dhamtari', state_id: '7', id: 144 },
  { name: 'Dhanbad', state_id: '16', id: 145 },
  { name: 'Dhar', state_id: '20', id: 146 },
  { name: 'Dharmapuri', state_id: '31', id: 147 },
  { name: 'Dharwad', state_id: '17', id: 148 },
  { name: 'Dhemaji', state_id: '4', id: 149 },
  { name: 'Dhenkanal', state_id: '26', id: 150 },
  { name: 'Dholpur', state_id: '29', id: 151 },
  { name: 'Dhubri', state_id: '4', id: 152 },
  { name: 'Dhule', state_id: '21', id: 153 },
  { name: 'Dibang Valley', state_id: '3', id: 154 },
  { name: 'Dibrugarh', state_id: '4', id: 155 },
  { name: 'Dimapur', state_id: '25', id: 156 },
  { name: 'Dindigul', state_id: '31', id: 157 },
  { name: 'Dindori', state_id: '20', id: 158 },
  { name: 'Diu', state_id: '9', id: 159 },
  { name: 'Doda', state_id: '15', id: 160 },
  { name: 'Dumka', state_id: '16', id: 161 },
  { name: 'Dungarpur', state_id: '29', id: 162 },
  { name: 'Durg', state_id: '7', id: 163 },
  { name: 'East Champaran', state_id: '5', id: 164 },
  { name: 'East Delhi', state_id: '10', id: 165 },
  { name: 'East Garo Hills', state_id: '23', id: 166 },
  { name: 'East Godavari', state_id: '2', id: 167 },
  { name: 'East Kameng', state_id: '3', id: 168 },
  { name: 'East Khasi Hills', state_id: '23', id: 169 },
  { name: 'East Midnapore', state_id: '36', id: 170 },
  { name: 'East Nimar', state_id: '20', id: 171 },
  { name: 'East Siang', state_id: '3', id: 172 },
  { name: 'East Sikkim', state_id: '30', id: 173 },
  { name: 'East Singhbhum', state_id: '16', id: 174 },
  { name: 'Ernakulam', state_id: '18', id: 175 },
  { name: 'Erode', state_id: '31', id: 176 },
  { name: 'Etah', state_id: '34', id: 177 },
  { name: 'Etawah', state_id: '34', id: 178 },
  { name: 'Faizabad', state_id: '34', id: 179 },
  { name: 'Faridabad', state_id: '13', id: 180 },
  { name: 'Faridkot', state_id: '28', id: 181 },
  { name: 'Farrukhabad', state_id: '34', id: 182 },
  { name: 'Fatehabad', state_id: '13', id: 183 },
  { name: 'Fatehgarh Sahib', state_id: '28', id: 184 },
  { name: 'Fatehpur', state_id: '34', id: 185 },
  { name: 'Fazilka', state_id: '28', id: 186 },
  { name: 'Firozabad', state_id: '34', id: 187 },
  { name: 'Firozpur', state_id: '28', id: 188 },
  { name: 'Gadag', state_id: '17', id: 189 },
  { name: 'Gadchiroli', state_id: '21', id: 190 },
  { name: 'Gajapati', state_id: '26', id: 191 },
  { name: 'Gandhi Nagar', state_id: '12', id: 192 },
  { name: 'Ganganagar', state_id: '29', id: 193 },
  { name: 'Ganjam', state_id: '26', id: 194 },
  { name: 'Garhwa', state_id: '16', id: 195 },
  { name: 'Gariaband', state_id: '7', id: 196 },
  { name: 'Gautam Buddha Nagar', state_id: '34', id: 197 },
  { name: 'Gaya', state_id: '5', id: 198 },
  { name: 'Ghaziabad', state_id: '34', id: 199 },
  { name: 'Ghazipur', state_id: '34', id: 200 },
  { name: 'Giridh', state_id: '16', id: 201 },
  { name: 'Goalpara', state_id: '4', id: 202 },
  { name: 'Godda', state_id: '16', id: 203 },
  { name: 'Golaghat', state_id: '4', id: 204 },
  { name: 'Gonda', state_id: '34', id: 205 },
  { name: 'Gondia', state_id: '21', id: 206 },
  { name: 'Gopalganj', state_id: '5', id: 207 },
  { name: 'Gorakhpur', state_id: '34', id: 208 },
  { name: 'Gulbarga', state_id: '17', id: 209 },
  { name: 'Gumla', state_id: '16', id: 210 },
  { name: 'Guna', state_id: '20', id: 211 },
  { name: 'Guntur', state_id: '2', id: 212 },
  { name: 'Gurdaspur', state_id: '28', id: 213 },
  { name: 'Gurgaon', state_id: '13', id: 214 },
  { name: 'Gwalior', state_id: '20', id: 215 },
  { name: 'Hailakandi', state_id: '4', id: 216 },
  { name: 'Hamirpur', state_id: '34', id: 217 },
  { name: 'Hamirpur(HP)', state_id: '14', id: 218 },
  { name: 'Hanumangarh', state_id: '29', id: 219 },
  { name: 'Harda', state_id: '20', id: 220 },
  { name: 'Hardoi', state_id: '34', id: 221 },
  { name: 'Haridwar', state_id: '35', id: 222 },
  { name: 'Hassan', state_id: '17', id: 223 },
  { name: 'Hathras', state_id: '34', id: 224 },
  { name: 'Haveri', state_id: '17', id: 225 },
  { name: 'Hazaribag', state_id: '16', id: 226 },
  { name: 'Hingoli', state_id: '21', id: 227 },
  { name: 'Hisar', state_id: '13', id: 228 },
  { name: 'Hooghly', state_id: '36', id: 229 },
  { name: 'Hoshangabad', state_id: '20', id: 230 },
  { name: 'Hoshiarpur', state_id: '28', id: 231 },
  { name: 'Howrah', state_id: '36', id: 232 },
  { name: 'Hyderabad', state_id: '32', id: 233 },
  { name: 'Idukki', state_id: '18', id: 234 },
  { name: 'Imphal East', state_id: '22', id: 235 },
  { name: 'Imphal West', state_id: '22', id: 236 },
  { name: 'Indore', state_id: '20', id: 237 },
  { name: 'Jabalpur', state_id: '20', id: 238 },
  { name: 'Jagatsinghapur', state_id: '26', id: 239 },
  { name: 'Jaintia Hills', state_id: '23', id: 240 },
  { name: 'Jaipur', state_id: '29', id: 241 },
  { name: 'Jaisalmer', state_id: '29', id: 242 },
  { name: 'Jajapur', state_id: '26', id: 243 },
  { name: 'Jalandhar', state_id: '28', id: 244 },
  { name: 'Jalaun', state_id: '34', id: 245 },
  { name: 'Jalgaon', state_id: '21', id: 246 },
  { name: 'Jalna', state_id: '21', id: 247 },
  { name: 'Jalor', state_id: '29', id: 248 },
  { name: 'Jalpaiguri', state_id: '36', id: 249 },
  { name: 'Jammu', state_id: '15', id: 250 },
  { name: 'Jamnagar', state_id: '12', id: 251 },
  { name: 'Jamtara', state_id: '16', id: 252 },
  { name: 'Jamui', state_id: '5', id: 253 },
  { name: 'Janjgir-champa', state_id: '7', id: 254 },
  { name: 'Jashpur', state_id: '7', id: 255 },
  { name: 'Jaunpur', state_id: '34', id: 256 },
  { name: 'Jehanabad', state_id: '5', id: 257 },
  { name: 'Jhabua', state_id: '20', id: 258 },
  { name: 'Jhajjar', state_id: '13', id: 259 },
  { name: 'Jhalawar', state_id: '29', id: 260 },
  { name: 'Jhansi', state_id: '34', id: 261 },
  { name: 'Jharsuguda', state_id: '26', id: 262 },
  { name: 'Jhujhunu', state_id: '29', id: 263 },
  { name: 'Jind', state_id: '13', id: 264 },
  { name: 'Jodhpur', state_id: '29', id: 265 },
  { name: 'Jorhat', state_id: '4', id: 266 },
  { name: 'Junagadh', state_id: '12', id: 267 },
  { name: 'Jyotiba Phule Nagar', state_id: '34', id: 268 },
  { name: 'K.V.Rangareddy', state_id: '32', id: 269 },
  { name: 'Kachchh', state_id: '12', id: 270 },
  { name: 'Kaimur (Bhabua)', state_id: '5', id: 271 },
  { name: 'Kaithal', state_id: '13', id: 272 },
  { name: 'Kalahandi', state_id: '26', id: 273 },
  { name: 'Kamrup', state_id: '4', id: 274 },
  { name: 'Kanchipuram', state_id: '31', id: 275 },
  { name: 'Kandhamal', state_id: '26', id: 276 },
  { name: 'Kangra', state_id: '14', id: 277 },
  { name: 'Kanker', state_id: '7', id: 278 },
  { name: 'Kannauj', state_id: '34', id: 279 },
  { name: 'Kannur', state_id: '18', id: 280 },
  { name: 'Kanpur Dehat', state_id: '34', id: 281 },
  { name: 'Kanpur Nagar', state_id: '34', id: 282 },
  { name: 'Kanyakumari', state_id: '31', id: 283 },
  { name: 'Kapurthala', state_id: '28', id: 284 },
  { name: 'Karaikal', state_id: '27', id: 285 },
  { name: 'Karauli', state_id: '29', id: 286 },
  { name: 'Karbi Anglong', state_id: '4', id: 287 },
  { name: 'Kargil', state_id: '15', id: 288 },
  { name: 'Karim Nagar', state_id: '32', id: 289 },
  { name: 'Karimganj', state_id: '4', id: 290 },
  { name: 'Karnal', state_id: '13', id: 291 },
  { name: 'Karur', state_id: '31', id: 292 },
  { name: 'Kasargod', state_id: '18', id: 293 },
  { name: 'Kathua', state_id: '15', id: 294 },
  { name: 'Katihar', state_id: '5', id: 295 },
  { name: 'Katni', state_id: '20', id: 296 },
  { name: 'Kaushambi', state_id: '34', id: 297 },
  { name: 'Kawardha', state_id: '7', id: 298 },
  { name: 'Kendrapara', state_id: '26', id: 299 },
  { name: 'Kendujhar', state_id: '26', id: 300 },
  { name: 'Khagaria', state_id: '5', id: 301 },
  { name: 'Khammam', state_id: '32', id: 302 },
  { name: 'Khandwa', state_id: '20', id: 303 },
  { name: 'Khargone', state_id: '20', id: 304 },
  { name: 'Kheda', state_id: '12', id: 305 },
  { name: 'Kheri', state_id: '34', id: 306 },
  { name: 'Khorda', state_id: '26', id: 307 },
  { name: 'Khunti', state_id: '16', id: 308 },
  { name: 'Kinnaur', state_id: '14', id: 309 },
  { name: 'Kiphire', state_id: '25', id: 310 },
  { name: 'Kishanganj', state_id: '5', id: 311 },
  { name: 'Kodagu', state_id: '17', id: 312 },
  { name: 'Koderma', state_id: '16', id: 313 },
  { name: 'Kohima', state_id: '25', id: 314 },
  { name: 'Kokrajhar', state_id: '4', id: 315 },
  { name: 'Kolar', state_id: '17', id: 316 },
  { name: 'Kolasib', state_id: '24', id: 317 },
  { name: 'Kolhapur', state_id: '21', id: 318 },
  { name: 'Kolkata', state_id: '36', id: 319 },
  { name: 'Kollam', state_id: '18', id: 320 },
  { name: 'Koppal', state_id: '17', id: 321 },
  { name: 'Koraput', state_id: '26', id: 322 },
  { name: 'Korba', state_id: '7', id: 323 },
  { name: 'Koriya', state_id: '7', id: 324 },
  { name: 'Kota', state_id: '29', id: 325 },
  { name: 'Kottayam', state_id: '18', id: 326 },
  { name: 'Kozhikode', state_id: '18', id: 327 },
  { name: 'Krishna', state_id: '2', id: 328 },
  { name: 'Krishnagiri', state_id: '31', id: 329 },
  { name: 'Kulgam', state_id: '15', id: 330 },
  { name: 'Kullu', state_id: '14', id: 331 },
  { name: 'Kupwara', state_id: '15', id: 332 },
  { name: 'Kurnool', state_id: '2', id: 333 },
  { name: 'Kurukshetra', state_id: '13', id: 334 },
  { name: 'Kurung Kumey', state_id: '3', id: 335 },
  { name: 'Kushinagar', state_id: '34', id: 336 },
  { name: 'Lahul & Spiti', state_id: '14', id: 337 },
  { name: 'Lakhimpur', state_id: '4', id: 338 },
  { name: 'Lakhisarai', state_id: '5', id: 339 },
  { name: 'Lakshadweep', state_id: '19', id: 340 },
  { name: 'Lalitpur', state_id: '34', id: 341 },
  { name: 'Latehar', state_id: '16', id: 342 },
  { name: 'Latur', state_id: '21', id: 343 },
  { name: 'Lawngtlai', state_id: '24', id: 344 },
  { name: 'Leh', state_id: '15', id: 345 },
  { name: 'Lohardaga', state_id: '16', id: 346 },
  { name: 'Lohit', state_id: '3', id: 347 },
  { name: 'Longleng', state_id: '25', id: 348 },
  { name: 'Lower Dibang Valley', state_id: '3', id: 349 },
  { name: 'Lower Subansiri', state_id: '3', id: 350 },
  { name: 'Lucknow', state_id: '34', id: 351 },
  { name: 'Ludhiana', state_id: '28', id: 352 },
  { name: 'Lunglei', state_id: '24', id: 353 },
  { name: 'Madhepura', state_id: '5', id: 354 },
  { name: 'Madhubani', state_id: '5', id: 355 },
  { name: 'Madurai', state_id: '31', id: 356 },
  { name: 'Mahabub Nagar', state_id: '32', id: 357 },
  { name: 'Maharajganj', state_id: '34', id: 358 },
  { name: 'Mahasamund', state_id: '7', id: 359 },
  { name: 'Mahe', state_id: '27', id: 360 },
  { name: 'Mahendragarh', state_id: '13', id: 361 },
  { name: 'Mahesana', state_id: '12', id: 362 },
  { name: 'Mahoba', state_id: '34', id: 363 },
  { name: 'Mainpuri', state_id: '34', id: 364 },
  { name: 'Malappuram', state_id: '18', id: 365 },
  { name: 'Malda', state_id: '36', id: 366 },
  { name: 'Malkangiri', state_id: '26', id: 367 },
  { name: 'Mammit', state_id: '24', id: 368 },
  { name: 'Mandi', state_id: '14', id: 369 },
  { name: 'Mandla', state_id: '20', id: 370 },
  { name: 'Mandsaur', state_id: '20', id: 371 },
  { name: 'Mandya', state_id: '17', id: 372 },
  { name: 'Mansa', state_id: '28', id: 373 },
  { name: 'Marigaon', state_id: '4', id: 374 },
  { name: 'Mathura', state_id: '34', id: 375 },
  { name: 'Mau', state_id: '34', id: 376 },
  { name: 'Mayurbhanj', state_id: '26', id: 377 },
  { name: 'Medak', state_id: '32', id: 378 },
  { name: 'Medinipur', state_id: '36', id: 379 },
  { name: 'Meerut', state_id: '34', id: 380 },
  { name: 'Mirzapur', state_id: '34', id: 381 },
  { name: 'Moga', state_id: '28', id: 382 },
  { name: 'Mohali', state_id: '28', id: 383 },
  { name: 'Mokokchung', state_id: '25', id: 384 },
  { name: 'Mon', state_id: '25', id: 385 },
  { name: 'Moradabad', state_id: '34', id: 386 },
  { name: 'Morena', state_id: '20', id: 387 },
  { name: 'Muktsar', state_id: '28', id: 388 },
  { name: 'Mumbai', state_id: '21', id: 389 },
  { name: 'Munger', state_id: '5', id: 390 },
  { name: 'Murshidabad', state_id: '36', id: 391 },
  { name: 'Muzaffarnagar', state_id: '34', id: 392 },
  { name: 'Muzaffarpur', state_id: '5', id: 393 },
  { name: 'Mysore', state_id: '17', id: 394 },
  { name: 'Nabarangapur', state_id: '26', id: 395 },
  { name: 'Nadia', state_id: '36', id: 396 },
  { name: 'Nagaon', state_id: '4', id: 397 },
  { name: 'Nagapattinam', state_id: '31', id: 398 },
  { name: 'Nagaur', state_id: '29', id: 399 },
  { name: 'Nagpur', state_id: '21', id: 400 },
  { name: 'Nainital', state_id: '35', id: 401 },
  { name: 'Nalanda', state_id: '5', id: 402 },
  { name: 'Nalbari', state_id: '4', id: 403 },
  { name: 'Nalgonda', state_id: '32', id: 404 },
  { name: 'Namakkal', state_id: '31', id: 405 },
  { name: 'Nanded', state_id: '21', id: 406 },
  { name: 'Nandurbar', state_id: '21', id: 407 },
  { name: 'Narayanpur', state_id: '7', id: 408 },
  { name: 'Narmada', state_id: '12', id: 409 },
  { name: 'Narsinghpur', state_id: '20', id: 410 },
  { name: 'Nashik', state_id: '21', id: 411 },
  { name: 'Navsari', state_id: '12', id: 412 },
  { name: 'Nawada', state_id: '5', id: 413 },
  { name: 'Nawanshahr', state_id: '28', id: 414 },
  { name: 'Nayagarh', state_id: '26', id: 415 },
  { name: 'Neemuch', state_id: '20', id: 416 },
  { name: 'Nellore', state_id: '2', id: 417 },
  { name: 'New Delhi', state_id: '10', id: 418 },
  { name: 'Nicobar', state_id: '1', id: 419 },
  { name: 'Nilgiris', state_id: '31', id: 420 },
  { name: 'Nizamabad', state_id: '32', id: 421 },
  { name: 'North 24 Parganas', state_id: '36', id: 422 },
  { name: 'North And Middle Andaman', state_id: '1', id: 423 },
  { name: 'North Cachar Hills', state_id: '4', id: 424 },
  { name: 'North Delhi', state_id: '10', id: 425 },
  { name: 'North Dinajpur', state_id: '36', id: 426 },
  { name: 'North East Delhi', state_id: '10', id: 427 },
  { name: 'North Goa', state_id: '11', id: 428 },
  { name: 'North Sikkim', state_id: '30', id: 429 },
  { name: 'North Tripura', state_id: '33', id: 430 },
  { name: 'North West Delhi', state_id: '10', id: 431 },
  { name: 'Nuapada', state_id: '26', id: 432 },
  { name: 'Osmanabad', state_id: '21', id: 433 },
  { name: 'Pakur', state_id: '16', id: 434 },
  { name: 'Palakkad', state_id: '18', id: 435 },
  { name: 'Palamau', state_id: '16', id: 436 },
  { name: 'Pali', state_id: '29', id: 437 },
  { name: 'Panch Mahals', state_id: '12', id: 438 },
  { name: 'Panchkula', state_id: '13', id: 439 },
  { name: 'Panipat', state_id: '13', id: 440 },
  { name: 'Panna', state_id: '20', id: 441 },
  { name: 'Papum Pare', state_id: '3', id: 442 },
  { name: 'Parbhani', state_id: '21', id: 443 },
  { name: 'Patan', state_id: '12', id: 444 },
  { name: 'Pathanamthitta', state_id: '18', id: 445 },
  { name: 'Pathankot', state_id: '28', id: 446 },
  { name: 'Patiala', state_id: '28', id: 447 },
  { name: 'Patna', state_id: '5', id: 448 },
  { name: 'Pauri Garhwal', state_id: '35', id: 449 },
  { name: 'Perambalur', state_id: '31', id: 450 },
  { name: 'Peren', state_id: '25', id: 451 },
  { name: 'Phek', state_id: '25', id: 452 },
  { name: 'Pilibhit', state_id: '34', id: 453 },
  { name: 'Pithoragarh', state_id: '35', id: 454 },
  { name: 'Pondicherry', state_id: '27', id: 455 },
  { name: 'Poonch', state_id: '15', id: 456 },
  { name: 'Porbandar', state_id: '12', id: 457 },
  { name: 'Prakasam', state_id: '2', id: 458 },
  { name: 'Pratapgarh', state_id: '34', id: 459 },
  { name: 'Pudukkottai', state_id: '31', id: 460 },
  { name: 'Pulwama', state_id: '15', id: 461 },
  { name: 'Pune', state_id: '21', id: 462 },
  { name: 'Puri', state_id: '26', id: 463 },
  { name: 'Purnia', state_id: '5', id: 464 },
  { name: 'Puruliya', state_id: '36', id: 465 },
  { name: 'Raebareli', state_id: '34', id: 466 },
  { name: 'Raichur', state_id: '17', id: 467 },
  { name: 'Raigarh', state_id: '7', id: 468 },
  { name: 'Raigarh(MH)', state_id: '21', id: 469 },
  { name: 'Raipur', state_id: '7', id: 470 },
  { name: 'Raisen', state_id: '20', id: 471 },
  { name: 'Rajauri', state_id: '15', id: 472 },
  { name: 'Rajgarh', state_id: '20', id: 473 },
  { name: 'Rajkot', state_id: '12', id: 474 },
  { name: 'Rajnandgaon', state_id: '7', id: 475 },
  { name: 'Rajsamand', state_id: '29', id: 476 },
  { name: 'Ramanagar', state_id: '17', id: 477 },
  { name: 'Ramanathapuram', state_id: '31', id: 478 },
  { name: 'Ramgarh', state_id: '16', id: 479 },
  { name: 'Rampur', state_id: '34', id: 480 },
  { name: 'Ranchi', state_id: '16', id: 481 },
  { name: 'Ratlam', state_id: '20', id: 482 },
  { name: 'Ratnagiri', state_id: '21', id: 483 },
  { name: 'Rayagada', state_id: '26', id: 484 },
  { name: 'Reasi', state_id: '15', id: 485 },
  { name: 'Rewa', state_id: '20', id: 486 },
  { name: 'Rewari', state_id: '13', id: 487 },
  { name: 'Ri Bhoi', state_id: '23', id: 488 },
  { name: 'Rohtak', state_id: '13', id: 489 },
  { name: 'Rohtas', state_id: '5', id: 490 },
  { name: 'Ropar', state_id: '28', id: 491 },
  { name: 'Rudraprayag', state_id: '35', id: 492 },
  { name: 'Rupnagar', state_id: '28', id: 493 },
  { name: 'Sabarkantha', state_id: '12', id: 494 },
  { name: 'Sagar', state_id: '20', id: 495 },
  { name: 'Saharanpur', state_id: '34', id: 496 },
  { name: 'Saharsa', state_id: '5', id: 497 },
  { name: 'Sahibganj', state_id: '16', id: 498 },
  { name: 'Saiha', state_id: '24', id: 499 },
  { name: 'Salem', state_id: '31', id: 500 },
  { name: 'Samastipur', state_id: '5', id: 501 },
  { name: 'Sambalpur', state_id: '26', id: 502 },
  { name: 'Sangli', state_id: '21', id: 503 },
  { name: 'Sangrur', state_id: '28', id: 504 },
  { name: 'Sant Kabir Nagar', state_id: '34', id: 505 },
  { name: 'Sant Ravidas Nagar', state_id: '34', id: 506 },
  { name: 'Saran', state_id: '5', id: 507 },
  { name: 'Satara', state_id: '21', id: 508 },
  { name: 'Satna', state_id: '20', id: 509 },
  { name: 'Sawai Madhopur', state_id: '29', id: 510 },
  { name: 'Sehore', state_id: '20', id: 511 },
  { name: 'Senapati', state_id: '22', id: 512 },
  { name: 'Seoni', state_id: '20', id: 513 },
  { name: 'Seraikela-kharsawan', state_id: '16', id: 514 },
  { name: 'Serchhip', state_id: '24', id: 515 },
  { name: 'Shahdol', state_id: '20', id: 516 },
  { name: 'Shahjahanpur', state_id: '34', id: 517 },
  { name: 'Shajapur', state_id: '20', id: 518 },
  { name: 'Sheikhpura', state_id: '5', id: 519 },
  { name: 'Sheohar', state_id: '5', id: 520 },
  { name: 'Sheopur', state_id: '20', id: 521 },
  { name: 'Shimla', state_id: '14', id: 522 },
  { name: 'Shimoga', state_id: '17', id: 523 },
  { name: 'Shivpuri', state_id: '20', id: 524 },
  { name: 'Shopian', state_id: '15', id: 525 },
  { name: 'Shrawasti', state_id: '34', id: 526 },
  { name: 'Sibsagar', state_id: '4', id: 527 },
  { name: 'Siddharthnagar', state_id: '34', id: 528 },
  { name: 'Sidhi', state_id: '20', id: 529 },
  { name: 'Sikar', state_id: '29', id: 530 },
  { name: 'Simdega', state_id: '16', id: 531 },
  { name: 'Sindhudurg', state_id: '21', id: 532 },
  { name: 'Singrauli', state_id: '20', id: 533 },
  { name: 'Sirmaur', state_id: '14', id: 534 },
  { name: 'Sirohi', state_id: '29', id: 535 },
  { name: 'Sirsa', state_id: '13', id: 536 },
  { name: 'Sitamarhi', state_id: '5', id: 537 },
  { name: 'Sitapur', state_id: '34', id: 538 },
  { name: 'Sivaganga', state_id: '31', id: 539 },
  { name: 'Siwan', state_id: '5', id: 540 },
  { name: 'Solan', state_id: '14', id: 541 },
  { name: 'Solapur', state_id: '21', id: 542 },
  { name: 'Sonapur', state_id: '26', id: 543 },
  { name: 'Sonbhadra', state_id: '34', id: 544 },
  { name: 'Sonipat', state_id: '13', id: 545 },
  { name: 'Sonitpur', state_id: '4', id: 546 },
  { name: 'South 24 Parganas', state_id: '36', id: 547 },
  { name: 'South Andaman', state_id: '1', id: 548 },
  { name: 'South Delhi', state_id: '10', id: 549 },
  { name: 'South Dinajpur', state_id: '36', id: 550 },
  { name: 'South Garo Hills', state_id: '23', id: 551 },
  { name: 'South Goa', state_id: '11', id: 552 },
  { name: 'South Sikkim', state_id: '30', id: 553 },
  { name: 'South Tripura', state_id: '33', id: 554 },
  { name: 'South West Delhi', state_id: '10', id: 555 },
  { name: 'Srikakulam', state_id: '2', id: 556 },
  { name: 'Srinagar', state_id: '15', id: 557 },
  { name: 'Sultanpur', state_id: '34', id: 558 },
  { name: 'Sundergarh', state_id: '26', id: 559 },
  { name: 'Supaul', state_id: '5', id: 560 },
  { name: 'Surat', state_id: '12', id: 561 },
  { name: 'Surendra Nagar', state_id: '12', id: 562 },
  { name: 'Surguja', state_id: '7', id: 563 },
  { name: 'Tamenglong', state_id: '22', id: 564 },
  { name: 'Tapi', state_id: '12', id: 565 },
  { name: 'Tarn Taran', state_id: '28', id: 566 },
  { name: 'Tawang', state_id: '3', id: 567 },
  { name: 'Tehri Garhwal', state_id: '35', id: 568 },
  { name: 'Thane', state_id: '21', id: 569 },
  { name: 'Thanjavur', state_id: '31', id: 570 },
  { name: 'The Dangs', state_id: '12', id: 571 },
  { name: 'Theni', state_id: '31', id: 572 },
  { name: 'Thiruvananthapuram', state_id: '18', id: 573 },
  { name: 'Thoubal', state_id: '22', id: 574 },
  { name: 'Thrissur', state_id: '18', id: 575 },
  { name: 'Tikamgarh', state_id: '20', id: 576 },
  { name: 'Tinsukia', state_id: '4', id: 577 },
  { name: 'Tirap', state_id: '3', id: 578 },
  { name: 'Tiruchirappalli', state_id: '31', id: 579 },
  { name: 'Tirunelveli', state_id: '31', id: 580 },
  { name: 'Tiruvallur', state_id: '31', id: 581 },
  { name: 'Tiruvannamalai', state_id: '31', id: 582 },
  { name: 'Tiruvarur', state_id: '31', id: 583 },
  { name: 'Tonk', state_id: '29', id: 584 },
  { name: 'Tuensang', state_id: '25', id: 585 },
  { name: 'Tumkur', state_id: '17', id: 586 },
  { name: 'Tuticorin', state_id: '31', id: 587 },
  { name: 'Udaipur', state_id: '29', id: 588 },
  { name: 'Udham Singh Nagar', state_id: '35', id: 589 },
  { name: 'Udhampur', state_id: '15', id: 590 },
  { name: 'Udupi', state_id: '17', id: 591 },
  { name: 'Ujjain', state_id: '20', id: 592 },
  { name: 'Ukhrul', state_id: '22', id: 593 },
  { name: 'Umaria', state_id: '20', id: 594 },
  { name: 'Una', state_id: '14', id: 595 },
  { name: 'Unnao', state_id: '34', id: 596 },
  { name: 'Upper Siang', state_id: '3', id: 597 },
  { name: 'Upper Subansiri', state_id: '3', id: 598 },
  { name: 'Uttara Kannada', state_id: '17', id: 599 },
  { name: 'Uttarkashi', state_id: '35', id: 600 },
  { name: 'Vadodara', state_id: '12', id: 601 },
  { name: 'Vaishali', state_id: '5', id: 602 },
  { name: 'Valsad', state_id: '12', id: 603 },
  { name: 'Varanasi', state_id: '34', id: 604 },
  { name: 'Vellore', state_id: '31', id: 605 },
  { name: 'Vidisha', state_id: '20', id: 606 },
  { name: 'Villupuram', state_id: '31', id: 607 },
  { name: 'Virudhunagar', state_id: '31', id: 608 },
  { name: 'Visakhapatnam', state_id: '2', id: 609 },
  { name: 'Vizianagaram', state_id: '2', id: 610 },
  { name: 'Warangal', state_id: '32', id: 611 },
  { name: 'Wardha', state_id: '21', id: 612 },
  { name: 'Washim', state_id: '21', id: 613 },
  { name: 'Wayanad', state_id: '18', id: 614 },
  { name: 'West Champaran', state_id: '5', id: 615 },
  { name: 'West Delhi', state_id: '10', id: 616 },
  { name: 'West Garo Hills', state_id: '23', id: 617 },
  { name: 'West Godavari', state_id: '2', id: 618 },
  { name: 'West Kameng', state_id: '3', id: 619 },
  { name: 'West Khasi Hills', state_id: '23', id: 620 },
  { name: 'West Midnapore', state_id: '36', id: 621 },
  { name: 'West Nimar', state_id: '20', id: 622 },
  { name: 'West Siang', state_id: '3', id: 623 },
  { name: 'West Sikkim', state_id: '30', id: 624 },
  { name: 'West Singhbhum', state_id: '16', id: 625 },
  { name: 'West Tripura', state_id: '33', id: 626 },
  { name: 'Wokha', state_id: '25', id: 627 },
  { name: 'Yadgir', state_id: '17', id: 628 },
  { name: 'Yamuna Nagar', state_id: '13', id: 629 },
  { name: 'Yavatmal', state_id: '21', id: 630 },
  { name: 'Zunhebotto', state_id: '25', id: 631 },
];
